server:
  port: 8048

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://SERVICE-A
          predicates:
            - Path=/serviceA/**
          filters:
            - StripPrefix=1

        - id: serviceB
          uri: lb://SERVICE-B
          predicates:
            - Path=/serviceB/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
